// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eeidevcyxpnorbgcskdf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVlaWRldmN5eHBub3JiZ2Nza2RmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExNDY4NTIsImV4cCI6MjA2NjcyMjg1Mn0.d_522xNkZuA5upBT0TuqoIW8ylxTCVhYy3YAHp55xdg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});